// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: lcder2

#include "ui.h"
#include "ui_helpers.h"
#include "../GUI/src/extra/themes/mono/lv_theme_mono.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_LabelAddr;
lv_obj_t * ui_LabelWeatherIcon;
lv_obj_t * ui_LabelDate;
lv_obj_t * ui_LabelTemp;
lv_obj_t * ui_LabelWeatherIcon1;
lv_obj_t * ui_LabelTemp1;
lv_obj_t * ui_LabelTime;
lv_obj_t * ui_LabelWeather;
lv_obj_t * ui_LabelWeather1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 8
    #error "LV_COLOR_DEPTH should be 8bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_mono_init(dispp, false, &lv_font_montserrat_18);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
