// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: lcder2

#ifndef _LCDER2_UI_H
#define _LCDER2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../GUI/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_LabelAddr;
extern lv_obj_t * ui_LabelDate;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_WeatherViewport;
extern lv_obj_t * ui_WeatherContent;
extern lv_obj_t * ui_WeatherPageNow;
extern lv_obj_t * ui_WeatherPageToday;
extern lv_obj_t * ui_WeatherPageTomorrow;
extern lv_obj_t * ui_LabelNowTitle;
extern lv_obj_t * ui_LabelNowIcon;
extern lv_obj_t * ui_LabelNowText;
extern lv_obj_t * ui_LabelNowTemp;
extern lv_obj_t * ui_LabelNowWindDir;
extern lv_obj_t * ui_LabelNowWindSpeed;
extern lv_obj_t * ui_LabelTodayTitle;
extern lv_obj_t * ui_LabelTodayIcon;
extern lv_obj_t * ui_LabelTodayText;
extern lv_obj_t * ui_LabelTodayTemp;
extern lv_obj_t * ui_LabelTodayWindDir;
extern lv_obj_t * ui_LabelTodayWindSpeed;
extern lv_obj_t * ui_LabelTomorrowTitle;
extern lv_obj_t * ui_LabelTomorrowIcon;
extern lv_obj_t * ui_LabelTomorrowText;
extern lv_obj_t * ui_LabelTomorrowTemp;
extern lv_obj_t * ui_LabelTomorrowWindDir;
extern lv_obj_t * ui_LabelTomorrowWindSpeed;

extern lv_obj_t * ui____initial_actions0;

LV_FONT_DECLARE(ui_font_digifaw);
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font1small);
LV_FONT_DECLARE(ui_font_iconfont);
LV_FONT_DECLARE(ui_font_iconfontSmall);
LV_FONT_DECLARE(ui_font_simli);
LV_FONT_DECLARE(ui_font_simliSmall);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
