// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: lcder2

#ifndef _LCDER2_UI_H
#define _LCDER2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../GUI/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_LabelAddr;
extern lv_obj_t * ui_LabelWeatherIcon;
extern lv_obj_t * ui_LabelDate;
extern lv_obj_t * ui_LabelTemp;
extern lv_obj_t * ui_LabelWeatherIcon1;
extern lv_obj_t * ui_LabelTemp1;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_LabelWeather;
extern lv_obj_t * ui_LabelWeather1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Calendar1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_digifaw);
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font1small);
LV_FONT_DECLARE(ui_font_iconfont);
LV_FONT_DECLARE(ui_font_iconfontSmall);
LV_FONT_DECLARE(ui_font_simli);
LV_FONT_DECLARE(ui_font_simliSmall);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
