// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: lcder2

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Calendar1 = lv_calendar_create(ui_Screen2);
    lv_calendar_set_today_date(ui_Calendar1, 2026, 1, 6);
    lv_calendar_set_showed_date(ui_Calendar1, 2026, 1);
    lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, 160);
    lv_obj_set_height(ui_Calendar1, 160);
    lv_obj_set_align(ui_Calendar1, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Calendar1, LV_SCROLLBAR_MODE_OFF);

}
