// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: lcder2

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelAddr = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelAddr, lv_pct(35));
    lv_obj_set_height(ui_LabelAddr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAddr, -50);
    lv_obj_set_y(ui_LabelAddr, 13);
    lv_obj_set_align(ui_LabelAddr, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelAddr, "莱山");
    lv_obj_set_style_text_color(ui_LabelAddr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAddr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelAddr, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAddr, &ui_font_simli, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeatherIcon = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelWeatherIcon, 50);
    lv_obj_set_height(ui_LabelWeatherIcon, 50);
    lv_obj_set_x(ui_LabelWeatherIcon, 12);
    lv_obj_set_y(ui_LabelWeatherIcon, 18);
    lv_obj_set_align(ui_LabelWeatherIcon, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelWeatherIcon, "A");
    lv_obj_set_style_text_color(ui_LabelWeatherIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeatherIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelWeatherIcon, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeatherIcon, &ui_font_iconfontSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDate = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelDate, lv_pct(61));
    lv_obj_set_height(ui_LabelDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDate, 30);
    lv_obj_set_y(ui_LabelDate, -110);
    lv_obj_set_align(ui_LabelDate, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelDate, "2025.4.17");
    lv_obj_set_style_text_color(ui_LabelDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelDate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDate, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTemp, lv_pct(32));
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, -43);
    lv_obj_set_y(ui_LabelTemp, -3);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelTemp, "20℃");
    lv_obj_set_style_text_color(ui_LabelTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp, &ui_font_simliSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeatherIcon1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelWeatherIcon1, 50);
    lv_obj_set_height(ui_LabelWeatherIcon1, 50);
    lv_obj_set_x(ui_LabelWeatherIcon1, 97);
    lv_obj_set_y(ui_LabelWeatherIcon1, 20);
    lv_obj_set_align(ui_LabelWeatherIcon1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelWeatherIcon1, "A");
    lv_obj_set_style_text_color(ui_LabelWeatherIcon1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeatherIcon1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelWeatherIcon1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeatherIcon1, &ui_font_iconfontSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemp1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTemp1, lv_pct(55));
    lv_obj_set_height(ui_LabelTemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp1, 33);
    lv_obj_set_y(ui_LabelTemp1, -3);
    lv_obj_set_align(ui_LabelTemp1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelTemp1, "10/20℃");
    lv_obj_set_style_text_color(ui_LabelTemp1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTemp1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp1, &ui_font_simliSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTime, lv_pct(61));
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime, 27);
    lv_obj_set_y(ui_LabelTime, -135);
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelTime, "10:08");
    lv_obj_set_style_text_color(ui_LabelTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTime, &ui_font_digifaw, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeather = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelWeather, lv_pct(39));
    lv_obj_set_height(ui_LabelWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeather, -44);
    lv_obj_set_y(ui_LabelWeather, 123);
    lv_obj_set_align(ui_LabelWeather, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelWeather, "晴");
    lv_obj_set_style_text_color(ui_LabelWeather, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelWeather, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeather, &ui_font_simliSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeather1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelWeather1, lv_pct(29));
    lv_obj_set_height(ui_LabelWeather1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeather1, 41);
    lv_obj_set_y(ui_LabelWeather1, 123);
    lv_obj_set_align(ui_LabelWeather1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelWeather1, "晴");
    lv_obj_set_style_text_color(ui_LabelWeather1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeather1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelWeather1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeather1, &ui_font_simliSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -44);
    lv_obj_set_y(ui_Label2, -20);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "今日");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_simliSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 42);
    lv_obj_set_y(ui_Label1, -20);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "明日");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_simliSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

}
